spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    cache: false
 
#  datasource: 
#    url: jdbc:oracle:thin:@1.234.63.35:1521:smartdb
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    username: gov
#    password: fnucni_2015 
#    #platform: 
  datasource: 
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: manager
    #platform: 
    
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect